spring.application.name=Mohamed-Youssef-Azzouz-4DS9

spring.datasource.url=jdbc:mysql://localhost:3306/Mohamed-Youssef-Azzouz-4DS9-Ski?createDatabaseIfNotExist=True

spring.datasource.username=root
spring.datasource.password=

server.port=8089

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
